#pragma once

#define PRODUCT_ID "wordclock-mini"
#define FIRMWARE_VERSION "mini-26.2.4"
#define UI_VERSION "ui-mini-26.2.4"
#define PRODUCT_VARIANT_MINI 1
#define DATA_PIN 7
#define SUPPORT_MINUTE_LEDS 0
#define SUPPORT_OTA_V2 0
#define BLE_PROVISIONING_ENABLED 1
#define WIFI_MANAGER_ENABLED 1
#define OTA_ENABLED 0
#define SETUP_BLINK_ENABLED 1
#define SETUP_BLINK_LED_COUNT 4
#define SETUP_BLINK_LED_IDS 1,9,97,105
