#pragma once

#define PRODUCT_ID "wordclock-mini"
#define FIRMWARE_VERSION "mini-26.2.18"
#define UI_VERSION "ui-mini-26.2.18"
#define PRODUCT_VARIANT_MINI 1
#define DATA_PIN 4
#define SETUP_ASSUME_DONE_IF_LEGACY_CONFIG 0
#define SUPPORT_MINUTE_LEDS 0
#define SUPPORT_OTA_V2 0
#define BLE_PROVISIONING_ENABLED 0
#define WIFI_MANAGER_ENABLED 1
#define OTA_ENABLED 0
#define LED_STATUS_EVENTS_ENABLED 1
#define LED_STATUS_EVENT_USE_MINUTE_LEDS 0
#define LED_STATUS_EVENT_LED_COUNT 4
#define LED_STATUS_EVENT_LED_IDS 1,9,97,105

// Log level: LOG_LEVEL_DEBUG, LOG_LEVEL_INFO, LOG_LEVEL_WARN, LOG_LEVEL_ERROR
// #define DEFAULT_LOG_LEVEL LOG_LEVEL_ERROR

// Update channel: "stable", "early", "develop"
// #define DEFAULT_UPDATE_CHANNEL "stable"
